/* GERADO por assets/build_skins.py — não edite à mão.
   Rode o script depois de mexer na arte e este arquivo se refaz.

   ICONES  : todo id que tem PNG próprio. data.js usa para achar a arte
             pelo id do item, então basta o arquivo se chamar como o id.
   ICONES2X: quem também tem @2x, para o srcset entregar 1:1 em tela densa. */
'use strict';
const ICONES = new Set(["ah_amulet", "ah_armor", "ah_backpack", "ah_boots", "ah_bow", "ah_hood", "ah_legs", "ah_quiver", "ah_ring", "ah_shield", "ai_amulet", "ai_armor", "ai_boots", "ai_hood", "ai_legs", "ai_ring", "ai_staff", "ai_tome", "armor", "axe", "beef", "bone", "boots", "boots_leather", "bow", "bronze_amulet", "coal", "cyclop_toe", "dagger", "feather", "fs_amulet", "fs_armor", "fs_boots", "fs_bow", "fs_hood", "fs_legs", "fs_ring", "fs_shield", "gem", "gg_amulet", "gg_armor", "gg_axe", "gg_boots", "gg_greataxe", "gg_greatsword", "gg_halberd", "gg_helmet", "gg_legs", "gg_mace", "gg_maul", "gg_ring", "gg_shield", "gg_sword", "glacier_rod", "great_health_potion", "great_mana_potion", "hailstorm_rod", "hand_axe", "health_potion", "helmet", "herb", "iron_amulet", "iron_axe", "iron_dagger", "iron_mace", "iron_ring", "iron_sword", "leather", "leather_armor", "leather_backpack", "leather_boots", "leather_helmet", "leather_hood", "leather_legs", "mace", "mana_potion", "moonlight_rod", "mushroom", "nature_staff", "ns_amulet", "ns_armor", "ns_boots", "ns_helmet", "ns_legs", "ns_ring", "ns_shield", "ns_sword", "orc_thooth", "poison_vial", "potion", "rope", "rune_fire", "sa_rod", "shell", "shield", "short_bow", "short_sword", "snakebite_rod", "spell_wand", "spider_fang", "spider_web", "spirit_staff", "springsprout_rod", "stance_attack", "stance_balanced", "stance_defense", "steak", "strong_health_potion", "strong_mana_potion", "sword", "terra_rod", "torch", "ui_bestiary", "ui_follow", "ui_map", "ui_settings", "ui_shop", "ui_sound_off", "ui_sound_on", "ui_stand", "voc_druid", "voc_knight", "voc_ranger", "voc_sorcerer", "void_wand", "vz_staff", "wand_of_cosmic_energy", "wand_of_decay", "wand_of_dragonbreath", "wand_of_inferno", "wand_of_vortex", "weak_health_potion", "wooden_bow", "wooden_shield", "worm"]);
const ICONES2X = new Set(["ah_amulet", "ah_armor", "ah_backpack", "ah_boots", "ah_bow", "ah_hood", "ah_legs", "ah_quiver", "ah_ring", "ah_shield", "ai_amulet", "ai_armor", "ai_boots", "ai_hood", "ai_legs", "ai_ring", "ai_staff", "ai_tome", "axe", "beef", "bone", "bow", "bronze_amulet", "coal", "cyclop_toe", "dagger", "feather", "fs_amulet", "fs_armor", "fs_boots", "fs_bow", "fs_hood", "fs_legs", "fs_ring", "fs_shield", "gem", "gg_amulet", "gg_armor", "gg_axe", "gg_boots", "gg_greataxe", "gg_greatsword", "gg_halberd", "gg_helmet", "gg_legs", "gg_mace", "gg_maul", "gg_ring", "gg_shield", "gg_sword", "glacier_rod", "great_health_potion", "great_mana_potion", "hailstorm_rod", "hand_axe", "health_potion", "herb", "iron_amulet", "iron_axe", "iron_dagger", "iron_mace", "iron_ring", "iron_sword", "leather", "leather_armor", "leather_backpack", "leather_boots", "leather_helmet", "leather_hood", "leather_legs", "mace", "mana_potion", "moonlight_rod", "mushroom", "nature_staff", "ns_amulet", "ns_armor", "ns_boots", "ns_helmet", "ns_legs", "ns_ring", "ns_shield", "ns_sword", "orc_thooth", "poison_vial", "potion", "rope", "sa_rod", "shell", "shield", "short_bow", "short_sword", "snakebite_rod", "spell_wand", "spider_fang", "spider_web", "spirit_staff", "springsprout_rod", "steak", "strong_health_potion", "strong_mana_potion", "sword", "terra_rod", "torch", "void_wand", "vz_staff", "wand_of_cosmic_energy", "wand_of_decay", "wand_of_dragonbreath", "wand_of_inferno", "wand_of_vortex", "weak_health_potion", "wooden_bow", "wooden_shield", "worm"]);
